// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alterusertoken.sql

package database

import (
	"context"
	"database/sql"
)

const updateUserToken = `-- name: UpdateUserToken :one
UPDATE users
SET authtoken = $1
WHERE name = $2
RETURNING id, created_at, updated_at, name, password_hash, is_admin, authtoken
`

type UpdateUserTokenParams struct {
	Authtoken sql.NullString
	Name      string
}

func (q *Queries) UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserToken, arg.Authtoken, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Authtoken,
	)
	return i, err
}
