// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finduserbyid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const findUserByID = `-- name: FindUserByID :one
SELECT id, created_at, updated_at, name, password_hash, is_admin, authtoken FROM users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Authtoken,
	)
	return i, err
}
